version: "3.9"
services:
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: crowdstreet
      POSTGRES_PASSWORD: crowdstreet
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres:
