version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: jerseyonspring
      POSTGRES_PASSWORD: jerseyonspring
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  mongo:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: jerseyonspring
      MONGO_INITDB_ROOT_PASSWORD: jerseyonspring
      MONGO_INITDB_DATABASE: jerseyonspring
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
volumes:
  postgres:
  mongo:
