spring:
  session:
    store-type: "mongodb"

  flyway:
    baseline-on-migrate: true

  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: crowdstreet
      username: crowdstreet
      password: crowdstreet

  datasource:
    url: "jdbc:postgresql://localhost:5432/crowdstreet"
    username: crowdstreet
    password: crowdstreet
  
  # Allow Jersey to work alongside Spring Web
  jersey:
    type: filter