spring:
  session:
    store-type: "mongodb"

  flyway:
    baseline-on-migrate: true

  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: jerseyonspring
      username: jerseyonspring
      password: jerseyonspring

  datasource:
    url: "jdbc:postgresql://localhost:5432/jerseyonspring"
    username: jerseyonspring
    password: jerseyonspring
  
  # Allow Jersey to work alongside Spring MVC
  jersey:
    type: filter